// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file project/v1/project.proto (package project.v1, syntax proto3)
/* eslint-disable */

import type {
    GenFile,
    GenMessage,
    GenService,
} from "@bufbuild/protobuf/codegenv1";
import {
    fileDesc,
    messageDesc,
    serviceDesc,
} from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file project/v1/project.proto.
 */
export const file_project_v1_project: GenFile =
    /*@__PURE__*/
    fileDesc(
        "Chhwcm9qZWN0L3YxL3Byb2plY3QucHJvdG8SCnByb2plY3QudjEidQoHUHJvamVjdBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhMKC2N1c3RvbWVyX2lkGAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAMSEgoKdXBkYXRlZF9hdBgGIAEoAyIfChFHZXRQcm9qZWN0UmVxdWVzdBIKCgJpZBgBIAEoCSI6ChJHZXRQcm9qZWN0UmVzcG9uc2USJAoHcHJvamVjdBgBIAEoCzITLnByb2plY3QudjEuUHJvamVjdCJHCg1DcmVhdGVQcm9qZWN0EgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSEwoLY3VzdG9tZXJfaWQYBCABKAkiQgoUQ3JlYXRlUHJvamVjdFJlcXVlc3QSKgoHcHJvamVjdBgBIAEoCzIZLnByb2plY3QudjEuQ3JlYXRlUHJvamVjdCI9ChVDcmVhdGVQcm9qZWN0UmVzcG9uc2USJAoHcHJvamVjdBgBIAEoCzITLnByb2plY3QudjEuUHJvamVjdCI8ChRVcGRhdGVQcm9qZWN0UmVxdWVzdBIkCgdwcm9qZWN0GAEgASgLMhMucHJvamVjdC52MS5Qcm9qZWN0Ij0KFVVwZGF0ZVByb2plY3RSZXNwb25zZRIkCgdwcm9qZWN0GAEgASgLMhMucHJvamVjdC52MS5Qcm9qZWN0IiIKFERlbGV0ZVByb2plY3RSZXF1ZXN0EgoKAmlkGAEgASgJIiMKFURlbGV0ZVByb2plY3RSZXNwb25zZRIKCgJpZBgBIAEoCSIUChJHZXRQcm9qZWN0c1JlcXVlc3QiPAoTR2V0UHJvamVjdHNSZXNwb25zZRIlCghwcm9qZWN0cxgBIAMoCzITLnByb2plY3QudjEuUHJvamVjdCIzChxHZXRQcm9qZWN0c0J5Q3VzdG9tZXJSZXF1ZXN0EhMKC2N1c3RvbWVyX2lkGAEgASgJIkYKHUdldFByb2plY3RzQnlDdXN0b21lclJlc3BvbnNlEiUKCHByb2plY3RzGAEgAygLMhMucHJvamVjdC52MS5Qcm9qZWN0Mp0ECg5Qcm9qZWN0U2VydmljZRJLCgpHZXRQcm9qZWN0Eh0ucHJvamVjdC52MS5HZXRQcm9qZWN0UmVxdWVzdBoeLnByb2plY3QudjEuR2V0UHJvamVjdFJlc3BvbnNlElQKDUNyZWF0ZVByb2plY3QSIC5wcm9qZWN0LnYxLkNyZWF0ZVByb2plY3RSZXF1ZXN0GiEucHJvamVjdC52MS5DcmVhdGVQcm9qZWN0UmVzcG9uc2USVAoNVXBkYXRlUHJvamVjdBIgLnByb2plY3QudjEuVXBkYXRlUHJvamVjdFJlcXVlc3QaIS5wcm9qZWN0LnYxLlVwZGF0ZVByb2plY3RSZXNwb25zZRJUCg1EZWxldGVQcm9qZWN0EiAucHJvamVjdC52MS5EZWxldGVQcm9qZWN0UmVxdWVzdBohLnByb2plY3QudjEuRGVsZXRlUHJvamVjdFJlc3BvbnNlEk4KC0dldFByb2plY3RzEh4ucHJvamVjdC52MS5HZXRQcm9qZWN0c1JlcXVlc3QaHy5wcm9qZWN0LnYxLkdldFByb2plY3RzUmVzcG9uc2USbAoVR2V0UHJvamVjdHNCeUN1c3RvbWVyEigucHJvamVjdC52MS5HZXRQcm9qZWN0c0J5Q3VzdG9tZXJSZXF1ZXN0GikucHJvamVjdC52MS5HZXRQcm9qZWN0c0J5Q3VzdG9tZXJSZXNwb25zZUI4WjZnaXRodWIuY29tL21heGlzY2htYXhpL2xqdGltZS1hcGkvcHJvamVjdC92MTtwcm9qZWN0djFiBnByb3RvMw"
    );

/**
 * @generated from message project.v1.Project
 */
export type Project = Message<"project.v1.Project"> & {
    /**
     * @generated from field: string id = 1;
     */
    id: string;

    /**
     * @generated from field: string name = 2;
     */
    name: string;

    /**
     * @generated from field: string description = 3;
     */
    description: string;

    /**
     * @generated from field: string customer_id = 4;
     */
    customerId: string;

    /**
     * @generated from field: int64 created_at = 5;
     */
    createdAt: bigint;

    /**
     * @generated from field: int64 updated_at = 6;
     */
    updatedAt: bigint;
};

/**
 * Describes the message project.v1.Project.
 * Use `create(ProjectSchema)` to create a new message.
 */
export const ProjectSchema: GenMessage<Project> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 0);

/**
 * @generated from message project.v1.GetProjectRequest
 */
export type GetProjectRequest = Message<"project.v1.GetProjectRequest"> & {
    /**
     * @generated from field: string id = 1;
     */
    id: string;
};

/**
 * Describes the message project.v1.GetProjectRequest.
 * Use `create(GetProjectRequestSchema)` to create a new message.
 */
export const GetProjectRequestSchema: GenMessage<GetProjectRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 1);

/**
 * @generated from message project.v1.GetProjectResponse
 */
export type GetProjectResponse = Message<"project.v1.GetProjectResponse"> & {
    /**
     * @generated from field: project.v1.Project project = 1;
     */
    project?: Project;
};

/**
 * Describes the message project.v1.GetProjectResponse.
 * Use `create(GetProjectResponseSchema)` to create a new message.
 */
export const GetProjectResponseSchema: GenMessage<GetProjectResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 2);

/**
 * @generated from message project.v1.CreateProject
 */
export type CreateProject = Message<"project.v1.CreateProject"> & {
    /**
     * @generated from field: string name = 2;
     */
    name: string;

    /**
     * @generated from field: string description = 3;
     */
    description: string;

    /**
     * @generated from field: string customer_id = 4;
     */
    customerId: string;
};

/**
 * Describes the message project.v1.CreateProject.
 * Use `create(CreateProjectSchema)` to create a new message.
 */
export const CreateProjectSchema: GenMessage<CreateProject> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 3);

/**
 * @generated from message project.v1.CreateProjectRequest
 */
export type CreateProjectRequest =
    Message<"project.v1.CreateProjectRequest"> & {
        /**
         * @generated from field: project.v1.CreateProject project = 1;
         */
        project?: CreateProject;
    };

/**
 * Describes the message project.v1.CreateProjectRequest.
 * Use `create(CreateProjectRequestSchema)` to create a new message.
 */
export const CreateProjectRequestSchema: GenMessage<CreateProjectRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 4);

/**
 * @generated from message project.v1.CreateProjectResponse
 */
export type CreateProjectResponse =
    Message<"project.v1.CreateProjectResponse"> & {
        /**
         * @generated from field: project.v1.Project project = 1;
         */
        project?: Project;
    };

/**
 * Describes the message project.v1.CreateProjectResponse.
 * Use `create(CreateProjectResponseSchema)` to create a new message.
 */
export const CreateProjectResponseSchema: GenMessage<CreateProjectResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 5);

/**
 * @generated from message project.v1.UpdateProjectRequest
 */
export type UpdateProjectRequest =
    Message<"project.v1.UpdateProjectRequest"> & {
        /**
         * @generated from field: project.v1.Project project = 1;
         */
        project?: Project;
    };

/**
 * Describes the message project.v1.UpdateProjectRequest.
 * Use `create(UpdateProjectRequestSchema)` to create a new message.
 */
export const UpdateProjectRequestSchema: GenMessage<UpdateProjectRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 6);

/**
 * @generated from message project.v1.UpdateProjectResponse
 */
export type UpdateProjectResponse =
    Message<"project.v1.UpdateProjectResponse"> & {
        /**
         * @generated from field: project.v1.Project project = 1;
         */
        project?: Project;
    };

/**
 * Describes the message project.v1.UpdateProjectResponse.
 * Use `create(UpdateProjectResponseSchema)` to create a new message.
 */
export const UpdateProjectResponseSchema: GenMessage<UpdateProjectResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 7);

/**
 * @generated from message project.v1.DeleteProjectRequest
 */
export type DeleteProjectRequest =
    Message<"project.v1.DeleteProjectRequest"> & {
        /**
         * @generated from field: string id = 1;
         */
        id: string;
    };

/**
 * Describes the message project.v1.DeleteProjectRequest.
 * Use `create(DeleteProjectRequestSchema)` to create a new message.
 */
export const DeleteProjectRequestSchema: GenMessage<DeleteProjectRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 8);

/**
 * @generated from message project.v1.DeleteProjectResponse
 */
export type DeleteProjectResponse =
    Message<"project.v1.DeleteProjectResponse"> & {
        /**
         * @generated from field: string id = 1;
         */
        id: string;
    };

/**
 * Describes the message project.v1.DeleteProjectResponse.
 * Use `create(DeleteProjectResponseSchema)` to create a new message.
 */
export const DeleteProjectResponseSchema: GenMessage<DeleteProjectResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 9);

/**
 * @generated from message project.v1.GetProjectsRequest
 */
export type GetProjectsRequest = Message<"project.v1.GetProjectsRequest"> & {};

/**
 * Describes the message project.v1.GetProjectsRequest.
 * Use `create(GetProjectsRequestSchema)` to create a new message.
 */
export const GetProjectsRequestSchema: GenMessage<GetProjectsRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 10);

/**
 * @generated from message project.v1.GetProjectsResponse
 */
export type GetProjectsResponse = Message<"project.v1.GetProjectsResponse"> & {
    /**
     * @generated from field: repeated project.v1.Project projects = 1;
     */
    projects: Project[];
};

/**
 * Describes the message project.v1.GetProjectsResponse.
 * Use `create(GetProjectsResponseSchema)` to create a new message.
 */
export const GetProjectsResponseSchema: GenMessage<GetProjectsResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 11);

/**
 * @generated from message project.v1.GetProjectsByCustomerRequest
 */
export type GetProjectsByCustomerRequest =
    Message<"project.v1.GetProjectsByCustomerRequest"> & {
        /**
         * @generated from field: string customer_id = 1;
         */
        customerId: string;
    };

/**
 * Describes the message project.v1.GetProjectsByCustomerRequest.
 * Use `create(GetProjectsByCustomerRequestSchema)` to create a new message.
 */
export const GetProjectsByCustomerRequestSchema: GenMessage<GetProjectsByCustomerRequest> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 12);

/**
 * @generated from message project.v1.GetProjectsByCustomerResponse
 */
export type GetProjectsByCustomerResponse =
    Message<"project.v1.GetProjectsByCustomerResponse"> & {
        /**
         * @generated from field: repeated project.v1.Project projects = 1;
         */
        projects: Project[];
    };

/**
 * Describes the message project.v1.GetProjectsByCustomerResponse.
 * Use `create(GetProjectsByCustomerResponseSchema)` to create a new message.
 */
export const GetProjectsByCustomerResponseSchema: GenMessage<GetProjectsByCustomerResponse> =
    /*@__PURE__*/
    messageDesc(file_project_v1_project, 13);

/**
 * @generated from service project.v1.ProjectService
 */
export const ProjectService: GenService<{
    /**
     * @generated from rpc project.v1.ProjectService.GetProject
     */
    getProject: {
        methodKind: "unary";
        input: typeof GetProjectRequestSchema;
        output: typeof GetProjectResponseSchema;
    };
    /**
     * @generated from rpc project.v1.ProjectService.CreateProject
     */
    createProject: {
        methodKind: "unary";
        input: typeof CreateProjectRequestSchema;
        output: typeof CreateProjectResponseSchema;
    };
    /**
     * @generated from rpc project.v1.ProjectService.UpdateProject
     */
    updateProject: {
        methodKind: "unary";
        input: typeof UpdateProjectRequestSchema;
        output: typeof UpdateProjectResponseSchema;
    };
    /**
     * @generated from rpc project.v1.ProjectService.DeleteProject
     */
    deleteProject: {
        methodKind: "unary";
        input: typeof DeleteProjectRequestSchema;
        output: typeof DeleteProjectResponseSchema;
    };
    /**
     * @generated from rpc project.v1.ProjectService.GetProjects
     */
    getProjects: {
        methodKind: "unary";
        input: typeof GetProjectsRequestSchema;
        output: typeof GetProjectsResponseSchema;
    };
    /**
     * @generated from rpc project.v1.ProjectService.GetProjectsByCustomer
     */
    getProjectsByCustomer: {
        methodKind: "unary";
        input: typeof GetProjectsByCustomerRequestSchema;
        output: typeof GetProjectsByCustomerResponseSchema;
    };
}> = /*@__PURE__*/ serviceDesc(file_project_v1_project, 0);
